from __future__ import annotations

import hashlib
import re
from pathlib import Path

from apexquant_migrations.models import MigrationEngine, MigrationFile

FILENAME_PATTERN = re.compile(r"^(\d{4,})_([a-z0-9_]+)\.sql$")
SLUG_PATTERN = re.compile(r"^[a-z0-9_]+$")


class MigrationDiscoveryError(Exception):
    pass


def compute_checksum(path: Path | str) -> str:
    path = Path(path)

    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_slug(slug: str) -> None:
    if not SLUG_PATTERN.match(slug):
        raise MigrationDiscoveryError(
            "migration slug may only contain lowercase letters, digits, and underscores"
        )


def discover_migrations(
    root: Path | str,
    engine: MigrationEngine,
    domain_filter: str | None = None,
) -> list[MigrationFile]:
    root = Path(root)

    if not root.exists():
        raise MigrationDiscoveryError(f"migration root does not exist: {root}")

    if not root.is_dir():
        raise MigrationDiscoveryError(f"migration root is not a directory: {root}")

    files: list[MigrationFile] = []

    for domain_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        domain = domain_dir.name

        if domain_filter is not None and domain != domain_filter:
            continue

        for sql_file in sorted(domain_dir.glob("*.sql")):
            match = FILENAME_PATTERN.match(sql_file.name)

            if match is None:
                raise MigrationDiscoveryError(
                    f"invalid migration filename: {sql_file}. "
                    "Expected format: NNNN_slug.sql"
                )

            version = match.group(1)

            migration_id = f"{engine.value}/{domain}/{sql_file.name}"

            files.append(
                MigrationFile(
                    engine=engine,
                    domain=domain,
                    filename=sql_file.name,
                    path=str(sql_file),
                    version=version,
                    migration_id=migration_id,
                    checksum_sha256=compute_checksum(sql_file),
                )
            )

    files.sort(key=lambda file: (file.domain, int(file.version), file.filename))

    return files


def next_version(existing: list[MigrationFile]) -> str:
    if not existing:
        return "0001"

    max_version = max(int(file.version) for file in existing)
    next_value = max_version + 1

    width = max(4, len(str(next_value)))

    return str(next_value).zfill(width)


def render_template(
    engine: MigrationEngine,
    domain: str,
    slug: str,
    version: str,
    filename: str,
) -> str:
    header = [
        "-- ApexQuant Ultra",
        f"-- Domain: {domain}",
        f"-- Migration: {filename}",
        "-- Generated by apexquant-migrate.",
        "",
    ]

    if engine == MigrationEngine.POSTGRES:
        body = [
            "BEGIN;",
            "",
            "SELECT 1;",
            "",
            "COMMIT;",
            "",
        ]
    else:
        body = [
            "SELECT 1;",
            "",
        ]

    return "\n".join(header + body)


def create_migration(
    root: Path | str,
    engine: MigrationEngine,
    domain: str,
    slug: str,
) -> Path:
    validate_slug(slug)

    root = Path(root)
    domain_dir = root / domain

    domain_dir.mkdir(parents=True, exist_ok=True)

    existing = discover_migrations(root, engine, domain_filter=domain)

    version = next_version(existing)
    filename = f"{version}_{slug}.sql"

    path = domain_dir / filename

    if path.exists():
        raise MigrationDiscoveryError(f"migration already exists: {path}")

    path.write_text(
        render_template(
            engine=engine,
            domain=domain,
            slug=slug,
            version=version,
            filename=filename,
        ),
        encoding="utf-8",
    )

    return path